### ISSUE TITLE
https://audius.org/developers returns 500

### ISSUE THREAD

**Issue by csjiang** [AudiusProject/audius-org-public-site#13]
On mobile web, the `Devs & Stakers` link in the footer of https://audius.co redirects to https://audius.org/developers, which returns a 500 response:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/21266692/127007501-24a7d15b-4c00-45b6-9dba-387f71d7b32c.png">

**Comment by dmanjunath** [comment]
Hey @csjiang thanks for pointing this out! We are actually planning to make some edits to the public site soon, we will add this to the list! @raymondjacobson

**Comment by raymondjacobson** [comment]
Thanks @csjiang!
fix is merged in https://github.com/AudiusProject/audius-client/pull/501
will be taken to production during the next web push. appreciate the find!
