### ISSUE TITLE
Conflux security warning

### ISSUE THREAD

**Issue by ChaozProgramming** [AudiusProject/audius-org-public-site#9]
Hi,
I havent taken the time to figure this out but i have the confluxportal app installed on firefox and everytime when i open the website this pops up.

![afbeelding](https://user-images.githubusercontent.com/28703878/114219671-40a46c80-996b-11eb-973e-1e3816318985.png)

Br
Pieter

**Comment by raymondjacobson** [comment]
Hi @ChaozProgramming thanks for flagging this. This shows when you visit audius.org?

**Comment by raymondjacobson** [comment]
I have tried to install confluxportal on firefox 89.0 and was able to access audius.co and audius.org.
@ChaozProgramming please re-open if you can provide a repro! thank you!
